import { collection, addDoc, Timestamp } from "firebase/firestore";
import { db } from "@/lib/firebase";

export const addSampleProducts = async () => {
  const products = [
    {
      name: "Premium Basmati Rice",
      description: "High-quality aged basmati rice, perfect for biryanis and pulao",
      category: "rice",
      price: "85.00",
      unit: "kg",
      stockQuantity: 500,
      minimumOrder: 5,
      deliveryTime: "Same day",
      supplierId: "supplier1",
      supplierName: "Shah Trading Co.",
      supplierLocation: "Karol Bagh, Delhi",
      imageUrl: "/uploads/basmati-rice.jpg",
      isActive: true,
      createdAt: Timestamp.now(),
    },
    {
      name: "Organic Turmeric Powder",
      description: "Pure organic turmeric powder, rich in curcumin",
      category: "spices",
      price: "120.00",
      unit: "kg",
      stockQuantity: 200,
      minimumOrder: 2,
      deliveryTime: "Same day",
      supplierId: "supplier1",
      supplierName: "Shah Trading Co.",
      supplierLocation: "Karol Bagh, Delhi",
      imageUrl: "/uploads/turmeric-powder.jpg",
      isActive: true,
      createdAt: Timestamp.now(),
    },
    {
      name: "Refined Sunflower Oil",
      description: "Light and healthy cooking oil, ideal for frying and cooking",
      category: "oil",
      price: "95.00",
      unit: "liter",
      stockQuantity: 300,
      minimumOrder: 3,
      deliveryTime: "Same day",
      supplierId: "supplier1",
      supplierName: "Shah Trading Co.",
      supplierLocation: "Karol Bagh, Delhi",
      imageUrl: "/uploads/sunflower-oil.jpg",
      isActive: true,
      createdAt: Timestamp.now(),
    },
    {
      name: "Fresh Onions",
      description: "Farm fresh red onions, essential for street food preparation",
      category: "vegetables",
      price: "25.00",
      unit: "kg",
      stockQuantity: 1000,
      minimumOrder: 10,
      deliveryTime: "Next day",
      supplierId: "supplier2",
      supplierName: "Gupta Wholesale",
      supplierLocation: "Chandni Chowk, Delhi",
      imageUrl: "/uploads/onions.jpg",
      isActive: true,
      createdAt: Timestamp.now(),
    },
    {
      name: "Fresh Tomatoes",
      description: "Ripe and juicy tomatoes, perfect for curries and chutneys",
      category: "vegetables",
      price: "30.00",
      unit: "kg",
      stockQuantity: 800,
      minimumOrder: 5,
      deliveryTime: "Next day",
      supplierId: "supplier2",
      supplierName: "Gupta Wholesale",
      supplierLocation: "Chandni Chowk, Delhi",
      imageUrl: "/uploads/tomatoes.jpg",
      isActive: true,
      createdAt: Timestamp.now(),
    },
    {
      name: "Wheat Flour",
      description: "High-quality wheat flour for rotis, naans, and bread",
      category: "flour",
      price: "35.00",
      unit: "kg",
      stockQuantity: 600,
      minimumOrder: 5,
      deliveryTime: "Same day",
      supplierId: "supplier1",
      supplierName: "Shah Trading Co.",
      supplierLocation: "Karol Bagh, Delhi",
      imageUrl: "/uploads/wheat-flour.jpg",
      isActive: true,
      createdAt: Timestamp.now(),
    },
    {
      name: "Garam Masala Powder",
      description: "Authentic blend of Indian spices for rich flavoring",
      category: "spices",
      price: "150.00",
      unit: "kg",
      stockQuantity: 100,
      minimumOrder: 1,
      deliveryTime: "Same day",
      supplierId: "supplier1",
      supplierName: "Shah Trading Co.",
      supplierLocation: "Karol Bagh, Delhi",
      imageUrl: "/uploads/garam-masala.jpg",
      isActive: true,
      createdAt: Timestamp.now(),
    },
    {
      name: "Fresh Potatoes",
      description: "High-quality potatoes, perfect for various street food dishes",
      category: "vegetables",
      price: "20.00",
      unit: "kg",
      stockQuantity: 1200,
      minimumOrder: 10,
      deliveryTime: "Next day",
      supplierId: "supplier2",
      supplierName: "Gupta Wholesale",
      supplierLocation: "Chandni Chowk, Delhi",
      imageUrl: "/uploads/potatoes.jpg",
      isActive: true,
      createdAt: Timestamp.now(),
    }
  ];

  try {
    for (const product of products) {
      await addDoc(collection(db, "products"), product);
    }
    console.log("Sample products added to Firebase successfully!");
  } catch (error) {
    console.error("Error adding sample products:", error);
  }
};